services:
  eia:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/eia:cached
    environment:
      - PYTHONPATH=/workspaces/eia